"""Despachos module - cliente delivery from warehouse"""
import os
import re
from datetime import datetime, date, timedelta
from typing import Optional, List

from fastapi import APIRouter, Depends, HTTPException, Query
from fastapi.responses import FileResponse
from sqlalchemy import and_, exists, func, or_
from sqlalchemy.exc import IntegrityError, OperationalError
from sqlalchemy.orm import Session, contains_eager
from pydantic import BaseModel

from database import get_db
from empresa_guard import require_empresa
from models.models import (
    Despacho, DespachoItem, OcCliente, Cotizacion, ItemCotizacion,
    Cliente, User, ReclamoProveedor, EmbarqueItem, Embarque,
    RecepcionEmbarque, RecepcionEmbarqueItem,
)
from auth import get_current_user
from notificaciones import crear_notificacion
from routers.compras import business_days_remaining, add_business_days
from wasabil_dte.models import (
    WasabilDte, STATUS_EMITIDO, STATUS_PROCESANDO, STATUS_PENDIENTE,
)
from wasabil_dte.service import TIPO_DOC_GUIA, claim_vigente, hoy_chile

# Despachos es data 100% Grupo AM (la tabla no tiene columna empresa): candado
# 'mineria' a nivel de router, igual que contabilidad y wasabil_dte.
router = APIRouter(
    prefix="/despachos",
    tags=["despachos"],
    dependencies=[Depends(require_empresa("mineria"))],
)

# Heuristic: a value generated by /docs/upload is a 32-hex UUID + extension
_UPLOAD_FILE_RE = re.compile(r"^[0-9a-f]{32}\.[A-Za-z0-9]{2,5}$")
_DOCS_DIR = os.path.abspath(
    os.path.join(os.path.dirname(os.path.dirname(__file__)), "uploads", "docs")
)


def _looks_like_upload(value: Optional[str]) -> bool:
    return bool(value and _UPLOAD_FILE_RE.match(value.strip()))


def _exists_in_docs(value: str) -> bool:
    """Check if value corresponds to a real file in DOCS_DIR (path-traversal safe)"""
    if not value or "/" in value or "\\" in value or ".." in value:
        return False
    candidate = os.path.abspath(os.path.join(_DOCS_DIR, value))
    if not candidate.startswith(_DOCS_DIR + os.sep):
        return False
    return os.path.isfile(candidate)


# Pipeline state buckets for the dispatch progress bar
_STATE_BUCKETS = {
    "ingresado": "pendiente",
    "cerrado": "pendiente",
    "comprado": "en_compras",
    "preparado": "en_transito",
    "pre_embarcado": "en_transito",
    "embarcado": "en_transito",
    "en_bodega": "en_bodega",
    "despachado": "despachado",
    "reclamo_proveedor": "reclamo",
}

_BUCKET_ORDER = ["pendiente", "en_compras", "en_transito", "en_bodega", "despachado", "reclamo"]


def _bucket_of(estado_item: Optional[str]) -> str:
    return _STATE_BUCKETS.get(estado_item or "", "pendiente")


def _item_deadline(item: ItemCotizacion, cot: Cotizacion, oc: OcCliente) -> Optional[date]:
    """Calculate the item-specific deadline:
    - If item has plazo_entrega_max AND cotización has created_at:
        deadline = cotizacion.created_at.date() + plazo_entrega_max business days
    - Else fallback to oc.fecha_entrega
    """
    if item.plazo_entrega_max and cot.created_at:
        try:
            ref = cot.created_at.date() if hasattr(cot.created_at, "date") else cot.created_at
            return add_business_days(ref, int(item.plazo_entrega_max))
        except Exception:
            pass
    if oc.fecha_entrega:
        return oc.fecha_entrega
    return None


# ── Buscador de operador (contrato común, 2026-08-05) ─────────────────────────
# Helpers PROPIOS de MachParts (docs/spec-buscadores-bodega-despachos-2026-08-05.md):
# la duplicación entre marcas es deliberada — se comparte la FORMA, no el código.
# Bodega (routers/bodega.py) los importa localmente, igual que ya hace con
# _qty_recibida_utilizable (patrón probado bodega→despachos, sin ciclo).
#
# Contrato del parámetro `q`:
#   · strip + colapsar espacios internos + truncar a 64 (pegados de Excel);
#   · menos de 2 caracteres = se ignora el filtro por completo;
#   · tokenizar por espacio, máximo 4 tokens: AND entre tokens, OR entre campos;
#   · por token, variante cruda + variante sin prefijo conocido — la UI imprime
#     "COT-2026-0001" en 8 pantallas pero la base guarda "2026-0001";
#   · escape de % y _ SIEMPRE: '_' tecleado es un guion bajo LITERAL (sin esto
#     '100_4567' matchea '100-4567' Y '100X4567' — dos partes distintas);
#   · .like() y NO .ilike(): las columnas son utf8mb4_unicode_ci (ya insensibles
#     a mayúsculas y tildes) y lower(col) anularía cualquier índice.

_Q_PREFIJOS_UI = ("COT-", "OC-", "OCP-", "EMB-", "DSP-", "N°", "Nº", "#")
_Q_MAX_LARGO = 64
_Q_MIN_LARGO = 2
_Q_MAX_TOKENS = 4


def _normalizar_q(q: Optional[str]) -> List[str]:
    """Término del operador → tokens normalizados (lista vacía = no filtrar)."""
    limpio = re.sub(r"\s+", " ", (q or "").strip())[:_Q_MAX_LARGO]
    if len(limpio) < _Q_MIN_LARGO:
        return []
    return limpio.split(" ")[:_Q_MAX_TOKENS]


def _variantes_token(tok: str) -> List[str]:
    """[cruda, sin prefijo conocido]: el operador copia lo que la pantalla imprime."""
    variantes = [tok]
    mayus = tok.upper()
    for pref in _Q_PREFIJOS_UI:
        if mayus.startswith(pref.upper()) and len(tok) > len(pref):
            resto = tok[len(pref):].strip()
            if len(resto) >= _Q_MIN_LARGO:
                variantes.append(resto)
            break
    return variantes


def _patron(v: str) -> str:
    """Patrón LIKE infijo con comodines escapados. Usar SIEMPRE como
    col.like(_patron(tok), escape="\\\\") — no es inyección SQL (el valor viaja
    bindeado), es comportamiento: sin escape, '_' devuelve la tabla entera."""
    for c in ("\\", "%", "_"):
        v = v.replace(c, "\\" + c)
    return f"%{v}%"


def _colapsar(tok: str) -> str:
    """Forma colapsada del número de parte: sin guiones ni espacios, mayúsculas.
    7T1997 y 7T-1997 conviven como filas distintas en la base (excel_service solo
    recorta), así que la pasada B compara ambas formas colapsadas."""
    return re.sub(r"[-\s]", "", tok).upper()


def _np_colapsado_sql(col):
    """Columna número de parte en forma colapsada (para la pasada B). Es un full
    scan reconocido: corre SOLO como red de seguridad cuando la pasada A dio 0."""
    return func.replace(func.replace(func.upper(col), "-", ""), " ", "")


def _matchea(valor, variantes_por_token) -> bool:
    """¿Algún token (en alguna de sus variantes) aparece en `valor`? Para la
    insignia de motivo, calculada SOLO sobre la página ya paginada (≤50 filas)."""
    v = (valor or "").lower()
    if not v:
        return False
    return any(any(x.lower() in v for x in vs) for vs in variantes_por_token)


def _filtro_q_oc_clientes(query, tokens: List[str], con_colapsado: bool = False):
    """Aplica `q` al listado de OC-Cliente EN SQL. Todo campo que vive en una
    tabla HIJA (ítems, embarques, despachos) entra como EXISTS correlacionado,
    NUNCA como .join(): un join a la colección multiplica la fila de la cabecera,
    infla query.count() y el LIMIT se come los cupos con duplicados."""
    for tok in tokens:
        conds = []
        for v in _variantes_token(tok):
            pat = _patron(v)
            conds += [
                OcCliente.numero_oc.like(pat, escape="\\"),
                Cotizacion.numero.like(pat, escape="\\"),
                Cotizacion.cliente.like(pat, escape="\\"),
                Cotizacion.rut_cliente.like(pat, escape="\\"),
                # Ítems de la cotización: n° de parte y el nombre que la pantalla
                # imprime (descripcion or nombre_cat — hay que mirar LAS DOS).
                exists().where(and_(
                    ItemCotizacion.cotizacion_id == Cotizacion.id,
                    or_(
                        ItemCotizacion.numero_parte.like(pat, escape="\\"),
                        ItemCotizacion.descripcion.like(pat, escape="\\"),
                        ItemCotizacion.nombre_cat.like(pat, escape="\\"),
                        ItemCotizacion.marca.like(pat, escape="\\"),
                    ),
                )),
                # Embarque que trajo los ítems. NUNCA Embarque.awb: guarda el
                # NOMBRE DEL ARCHIVO adjunto; el número real es awb_numero
                # (models/models.py:220-221 lo dice literal).
                exists().where(and_(
                    ItemCotizacion.cotizacion_id == Cotizacion.id,
                    EmbarqueItem.item_cotizacion_id == ItemCotizacion.id,
                    Embarque.id == EmbarqueItem.embarque_id,
                    or_(
                        Embarque.numero.like(pat, escape="\\"),
                        Embarque.awb_numero.like(pat, escape="\\"),
                    ),
                )),
                # Despachos de la OC: el N° de guía es el papel que el cliente
                # cita por teléfono y antes era imposible de buscar.
                exists().where(and_(
                    Despacho.oc_cliente_id == OcCliente.id,
                    or_(
                        Despacho.numero_despacho.like(pat, escape="\\"),
                        Despacho.numero_guia.like(pat, escape="\\"),
                        Despacho.numero_expedicion.like(pat, escape="\\"),
                        Despacho.transportista.like(pat, escape="\\"),
                    ),
                )),
            ]
        if con_colapsado and any(ch.isdigit() for ch in tok):
            # Pasada B: comparación colapsada del número de parte (sin guiones).
            conds.append(exists().where(and_(
                ItemCotizacion.cotizacion_id == Cotizacion.id,
                _np_colapsado_sql(ItemCotizacion.numero_parte)
                .like(_patron(_colapsar(tok)), escape="\\"),
            )))
        query = query.filter(or_(*conds))
    return query


# --- Schemas ---
class DespachoItemIn(BaseModel):
    item_cotizacion_id: int
    qty_despachada: float


class DespachoCreate(BaseModel):
    oc_cliente_id: int
    numero_guia: Optional[str] = None
    transportista: Optional[str] = None
    numero_expedicion: Optional[str] = None   # N° de expedición de la guía (todos sus ítems lo comparten)
    contacto_destinatario: Optional[str] = None
    direccion_entrega: Optional[str] = None
    observaciones: Optional[str] = None
    items: List[DespachoItemIn]


class DespachoUpdate(BaseModel):
    numero_guia: Optional[str] = None
    # Fecha de EMISIÓN de la guía ante el SII (YYYY-MM-DD), sólo para guía EN PAPEL.
    # Tri-estado gracias a exclude_unset: ausente = no tocar · "2026-07-15" = fijar ·
    # null/"" = borrar. Ver _parse_fecha_guia y models.Despacho.fecha_guia.
    fecha_guia: Optional[str] = None
    transportista: Optional[str] = None
    numero_expedicion: Optional[str] = None
    contacto_destinatario: Optional[str] = None
    direccion_entrega: Optional[str] = None
    observaciones: Optional[str] = None


class FirmarIn(BaseModel):
    fecha_firma: Optional[str] = None   # YYYY-MM-DD; por defecto hoy
    numero_guia: Optional[str] = None   # opcional: setear/confirmar el N° de guía al firmar
    archivo: Optional[str] = None       # nombre del archivo (foto/PDF) de la guía firmada, ya subido vía POST /api/compras/docs/upload


# --- Helpers ---
# Antigüedad máxima aceptada para la fecha de emisión de una guía tecleada a mano. No es
# una regla del SII: es una malla ANCHA contra el dedazo grueso (un 2019 en vez de un
# 2026), y 2 años deja pasar cualquier regularización real.
# OJO — lo que esta malla NO ataja: el typo de UN año ("2025-07-15" por "2026-07-15") cae
# muy dentro de los 730 días y pasa limpio. Bajar el tope no es la solución (bloquearía
# regularizaciones legítimas); el control que sí ataja el error hacia adelante es el cruce
# `guia_fecha <= fecha de la factura` de armar_referencias_factura (wasabil_dte/service.py),
# porque una guía fechada el año pasado sigue siendo anterior a su factura y sólo el
# operador sabe si es correcta.
_ANTIGUEDAD_MAX_FECHA_GUIA_DIAS = 730

# Formato aceptado: AAAA-MM-DD, opcionalmente con sufijo horario ISO. Cualquier otra cosa
# pegada a la fecha se RECHAZA en vez de truncarse (ver _parse_fecha_guia).
_RE_FECHA_GUIA = re.compile(r"^\d{4}-\d{2}-\d{2}([T ].*)?$")


def _parse_fecha_guia(valor) -> Optional[date]:
    """Texto YYYY-MM-DD → date, para la fecha de EMISIÓN de la guía en papel.

    Devuelve None cuando el operador la borra (null o ""), que es un estado legítimo:
    el despacho vuelve a "sin fecha" y la facturación electrónica se bloquea hasta que
    se cargue de nuevo.

    Valida ANTES de guardar porque esta fecha termina viajando como FchRef dentro de un
    DTE 33 REAL: una fecha inventada no se corrige después, sólo se anula el documento.
    Se rechaza:
      · lo que no sea una fecha YYYY-MM-DD,
      · una fecha FUTURA (una guía no se emite mañana; suele ser un tipeo),
      · una fecha absurdamente vieja (ver _ANTIGUEDAD_MAX_FECHA_GUIA_DIAS).
    """
    if valor is None:
        return None
    texto = str(valor).strip()
    if not texto:
        return None
    # `_RE_FECHA_GUIA` antes de strptime: con `texto[:10]` a secas, "2026-07-155" se
    # truncaba a "2026-07-15" y se aceptaba en silencio un dato que el operador escribió
    # mal. Se admite el sufijo horario ("2026-07-15T10:00:00") porque algunos clientes
    # mandan datetime ISO, pero nada más pegado a la fecha.
    if not _RE_FECHA_GUIA.match(texto):
        raise HTTPException(
            400,
            "La fecha de emisión de la guía debe tener el formato AAAA-MM-DD "
            f"(recibido: '{texto}')",
        )
    try:
        fecha = datetime.strptime(texto[:10], "%Y-%m-%d").date()
    except ValueError:
        # Formato correcto pero fecha inexistente: 2026-02-31, 2026-13-01.
        raise HTTPException(
            400,
            f"La fecha de emisión de la guía '{texto[:10]}' no existe en el calendario",
        )
    hoy = hoy_chile()
    if fecha > hoy:
        raise HTTPException(
            400,
            f"La fecha de emisión de la guía ({fecha.isoformat()}) es futura: "
            "revisa el dato (hoy en Chile es "
            f"{hoy.isoformat()}). Debe ser la fecha en que el SII emitió la guía.",
        )
    if (hoy - fecha).days > _ANTIGUEDAD_MAX_FECHA_GUIA_DIAS:
        raise HTTPException(
            400,
            f"La fecha de emisión de la guía ({fecha.isoformat()}) tiene más de "
            f"{_ANTIGUEDAD_MAX_FECHA_GUIA_DIAS // 365} años: revisa el año antes de "
            "guardar (es el error de tipeo más común).",
        )
    return fecha


def _next_numero_despacho(db: Session) -> str:
    year = datetime.now().year
    prefix = f"DSP-{year}-"
    last = (
        db.query(Despacho)
        .filter(Despacho.numero_despacho.like(f"{prefix}%"))
        .order_by(Despacho.id.desc())
        .first()
    )
    n = 0
    if last and last.numero_despacho:
        try:
            n = int(last.numero_despacho.split("-")[-1])
        except Exception:
            n = 0
    return f"{prefix}{n + 1:04d}"


def _qty_already_dispatched(db: Session, oc_id: int, con_lock: bool = False):
    """Return dict {item_cotizacion_id: total_qty_despachada} for non-cancelled despachos

    `con_lock=True` (creación de despachos): lee con SELECT ... FOR UPDATE para ver
    las cantidades COMMITEADAS más recientes aunque la transacción tenga un snapshot
    anterior (REPEATABLE READ) — cierra la carrera de dos despachos simultáneos de
    la misma OC. `populate_existing()` obligatorio: sin él, el identity map de
    SQLAlchemy devolvería los datos viejos del snapshot aunque el lock espere.
    """
    q = (
        db.query(DespachoItem.item_cotizacion_id, DespachoItem.qty_despachada)
        .join(Despacho, Despacho.id == DespachoItem.despacho_id)
        .filter(Despacho.oc_cliente_id == oc_id, Despacho.estado != "anulado")
    )
    if con_lock:
        q = q.populate_existing().with_for_update()
    rows = q.all()
    result = {}
    for item_id, qty in rows:
        result[item_id] = result.get(item_id, 0) + (qty or 0)
    return result


def _qty_dispatched_closed(db: Session, oc_id: int, con_lock: bool = False):
    """Σ qty por ítem SOLO de despachos CERRADOS ('despachado').

    Es la cobertura que decide el flip de la línea (y del embarque) al cerrar un
    despacho: un despacho abierto (en_preparacion) es un borrador anulable, no
    mercadería salida — contarlo marcaba 'despachado' prematuro con tandas
    abiertas (hallazgo del enjambre G16). Para el TOPE anti-sobredespacho de
    create_despacho sigue siendo correcta _qty_already_dispatched (abiertos y
    cerrados consumen cupo por igual)."""
    q = (
        db.query(DespachoItem.item_cotizacion_id, DespachoItem.qty_despachada)
        .join(Despacho, Despacho.id == DespachoItem.despacho_id)
        .filter(Despacho.oc_cliente_id == oc_id, Despacho.estado == "despachado")
    )
    if con_lock:
        q = q.populate_existing().with_for_update()
    rows = q.all()
    result = {}
    for item_id, qty in rows:
        result[item_id] = result.get(item_id, 0) + (qty or 0)
    return result


# Estados de recepción cuyas unidades quedan UTILIZABLES en bodega. 'faltante'
# está incluido porque su qty_recibida son las unidades que SÍ llegaron buenas
# (el faltante se reclama aparte); 'no_llego' y 'danado_no_utilizable' aportan 0.
_RECEPCION_UTILIZABLE = ("completo", "danado_utilizable", "sobrante", "faltante")


def _qty_recibida_utilizable(db: Session, item_ids):
    """{item_cotizacion_id: Σ qty_recibida utilizable} desde recepciones CERRADAS.

    Es el TOPE FÍSICO del despacho: no se puede despachar (ni emitir guía, ni
    facturar) más de lo que Bodega recibió realmente. Solo aparecen los ítems
    que TIENEN registro de recepción — un ítem sin recepción (flujo antiguo o
    carga manual a bodega) no se acota, para no romper datos históricos.

    Suma DOS fuentes en el MISMO dict por item_cotizacion_id: (1) recepciones de
    EMBARQUE cerradas utilizables (internacional), (2) recepciones NACIONALES
    cerradas utilizables. Aditivo y direccionalmente seguro: para un ítem nacional
    solo puede BAJAR el tope (de 'todo lo vendido' a min(vendido, recibido)); no
    toca los internacionales (fuente distinta, item_ids disjuntos por construcción)."""
    if not item_ids:
        return {}
    result = {}
    # ── Fuente 1: embarques internacionales (SIN CAMBIOS) ──
    rows = (
        db.query(EmbarqueItem.item_cotizacion_id, RecepcionEmbarqueItem.qty_recibida)
        .join(RecepcionEmbarqueItem,
              RecepcionEmbarqueItem.embarque_item_id == EmbarqueItem.id)
        .join(RecepcionEmbarque,
              RecepcionEmbarque.id == RecepcionEmbarqueItem.recepcion_id)
        .filter(
            EmbarqueItem.item_cotizacion_id.in_(item_ids),
            RecepcionEmbarque.estado == "cerrada",
            RecepcionEmbarqueItem.estado_recepcion.in_(_RECEPCION_UTILIZABLE),
        )
        .all()
    )
    for item_id, qty in rows:
        result[item_id] = result.get(item_id, 0) + max(qty or 0, 0)
    # ── Fuente 2: recepciones NACIONALES (UNION aditivo) ──
    # Import LOCAL (patrón probado bodega→despachos): recepcion_nacional.models NO
    # importa despachos → sin ciclo. Se reusa la MISMA constante _RECEPCION_UTILIZABLE.
    from recepcion_nacional.models import RecepcionNacional, RecepcionNacionalItem
    nac = (
        db.query(RecepcionNacionalItem.item_cotizacion_id, RecepcionNacionalItem.qty_recibida)
        .join(RecepcionNacional,
              RecepcionNacional.id == RecepcionNacionalItem.recepcion_id)
        .filter(
            RecepcionNacionalItem.item_cotizacion_id.in_(item_ids),
            RecepcionNacional.estado == "cerrada",
            RecepcionNacionalItem.estado_recepcion.in_(_RECEPCION_UTILIZABLE),
        )
        .all()
    )
    for item_id, qty in nac:
        if item_id is None:
            continue
        # float() en ambos operandos: evita mezclar Decimal (fuente nacional) con
        # el valor previo (int/Decimal de la fuente 1) → nunca TypeError.
        result[item_id] = float(result.get(item_id, 0)) + max(float(qty or 0), 0.0)
    return result


def _tope_fisico(item: ItemCotizacion, recibidos: dict) -> float:
    """Cantidad máxima despachable de la línea: lo RECIBIDO en bodega si hay
    recepción registrada (capado a la cantidad vendida), o la cantidad de la
    cotización si no la hay (comportamiento histórico)."""
    cant = item.cantidad or 0
    if item.id in recibidos:
        return min(cant, recibidos[item.id])
    return cant


def _guia_electronica_activa(db: Session, despacho_id: int, con_lock: bool = False,
                             incluir_ambiguo: bool = False) -> Optional[WasabilDte]:
    """Guía electrónica (SII 52) VIVA del despacho: emitida, en vuelo (claim) o en
    proceso en Wasabil. Mientras exista, las operaciones que la dejarían huérfana o
    pisarían su folio (anular el despacho, editar el N° de guía a mano) se rechazan:
    el folio es un documento tributario legal y su anulación se gestiona en Wasabil.
    Un DTE FALLIDO (rechazado por el SII, sin folio) no bloquea nada.

    `con_lock=True` (anular): lee con FOR UPDATE + populate_existing para ver el
    claim/estado COMMITEADO más reciente aunque la transacción tenga un snapshot
    anterior — cierra la carrera anular ↔ emitir.

    `incluir_ambiguo=True` (SOLO anular): además cuenta como viva la emisión
    AMBIGUA — uuid NULL pero `en_vuelo_desde` puesto — aunque su claim ya haya
    VENCIDO por TTL. Ahí Wasabil cortó la comunicación sin confirmar nada
    (timeout/5xx) y `_emitir_en_wasabil` conserva el timestamp a propósito: el
    documento PUDO nacer con folio real en el SII. Decidir por TTL dejaba anular el
    despacho, liberaba la mercadería y habilitaba una SEGUNDA guía 52 REAL por lo
    mismo (irreversible — y Grupo AM es la marca que YA emite de verdad), además de
    dejar el documento sin recuperación. Es el mismo `ambiguo_sin_resolver` que ya
    protege el borrado de facturas en routers/contabilidad.py. El fallo CONFIRMADO
    no queda atrapado: _emitir_en_wasabil limpia `en_vuelo_desde` cuando el error NO
    es ambiguo, así que un DTE fallido sigue permitiendo anular (el despacho nunca
    es imborrable).
    Por defecto False: el PUT de numero_guia (_rechazar_si_pisa_folio) NO es
    irreversible y ahí el criterio por TTL es el correcto — no se debe endurecer.

    Paridad con MonzaParts (monza_router_despachos.py:_guia_electronica_activa)."""
    q = (
        db.query(WasabilDte)
        .filter(WasabilDte.despacho_id == despacho_id,
                WasabilDte.tipo_dte == TIPO_DOC_GUIA)
    )
    if con_lock:
        q = q.populate_existing().with_for_update()
    dte = q.first()
    if not dte:
        return None
    if dte.status_id == STATUS_EMITIDO:
        return dte
    if claim_vigente(dte):
        return dte
    if dte.uuid and dte.status_id in (STATUS_PROCESANDO, STATUS_PENDIENTE):
        return dte
    # Emisión AMBIGUA con el claim ya vencido: sin uuid no sabemos si el documento
    # existe, pero `en_vuelo_desde` dice que el POST salió y nadie confirmó el
    # resultado. Solo bloquea a quien lo pide (anular).
    if incluir_ambiguo and dte.uuid is None and dte.en_vuelo_desde is not None:
        return dte
    return None


def _rechazar_si_pisa_folio(db: Session, d: Despacho, numero_guia_nuevo: Optional[str]):
    """Bloquea el cambio manual de numero_guia cuando el despacho tiene guía
    electrónica viva (el N° correcto es el folio del SII, lo escribe el módulo
    Wasabil). Dejar pasar el mismo valor actual es inofensivo (no-op)."""
    if (numero_guia_nuevo or "") == (d.numero_guia or ""):
        return
    dte = _guia_electronica_activa(db, d.id)
    if not dte:
        return
    if dte.folio:
        raise HTTPException(
            409,
            f"Este despacho tiene guía electrónica SII emitida (folio {dte.folio}): "
            "el N° de guía no se edita a mano",
        )
    raise HTTPException(
        409,
        "Este despacho tiene una emisión de guía SII en curso: el N° de guía "
        "quedará fijado por el folio del SII al terminar",
    )


def _serialize_oc_card(db: Session, oc: OcCliente, items=None, clientes_por_rut=None):
    """Serialize OC-Cliente for the dispatch list view

    `items` / `clientes_por_rut` permiten precargar en lote desde el listado
    (una query para todas las OCs en vez de 2 por OC); sin ellos, consulta
    individualmente como siempre (detalle de una sola OC).
    """
    cot = oc.cotizacion
    if not cot:
        return None
    cliente = None
    if clientes_por_rut is not None:
        cliente = clientes_por_rut.get(cot.rut_cliente) if cot.rut_cliente else None
    elif cot.rut_cliente:
        cliente = db.query(Cliente).filter(Cliente.rut == cot.rut_cliente).first()

    if items is None:
        items = (
            db.query(ItemCotizacion)
            .filter(ItemCotizacion.cotizacion_id == cot.id)
            .all()
        )
    total = len(items)
    en_bodega = sum(1 for i in items if i.estado_item == "en_bodega")
    despachados = sum(1 for i in items if i.estado_item == "despachado")
    no_dispon = total - en_bodega - despachados

    # Pipeline state breakdown for progress bar
    progreso_estados = {b: 0 for b in _BUCKET_ORDER}
    for it in items:
        progreso_estados[_bucket_of(it.estado_item)] += 1

    # OC-level days remaining (customer-facing deadline)
    dias_restantes_oc: Optional[int] = None
    if oc.fecha_entrega:
        try:
            dias_restantes_oc = business_days_remaining(oc.fecha_entrega)
        except Exception:
            dias_restantes_oc = None

    # Worst-case (most urgent) item deadline — the most constraining promise
    worst_item_days: Optional[int] = None
    for it in items:
        if it.estado_item == "despachado":
            continue
        dl = _item_deadline(it, cot, oc)
        if not dl:
            continue
        try:
            d = business_days_remaining(dl)
        except Exception:
            continue
        if worst_item_days is None or d < worst_item_days:
            worst_item_days = d

    if total == 0:
        progreso = 0
    else:
        progreso = int(despachados * 100 / total)

    if total and despachados == total:
        estado = "completado"
    elif despachados > 0 and en_bodega > 0:
        estado = "parcial"
    elif en_bodega > 0:
        estado = "listo"
    else:
        estado = "pendiente"

    return {
        "id": oc.id,
        "cotizacion_id": cot.id,
        "numero_oc": oc.numero_oc,
        "fecha_oc": oc.fecha_oc,
        "fecha_entrega": oc.fecha_entrega.isoformat() if oc.fecha_entrega else None,
        "cond_pago": oc.cond_pago,
        "cliente": cot.cliente,
        "rut_cliente": cot.rut_cliente,
        "direccion": (cliente.direccion if cliente else None) or cot.direccion_cliente,
        "contacto": (cliente.contacto if cliente else None) or cot.contacto_cliente,
        "telefono": (cliente.telefono if cliente else None) or cot.telefono_cliente,
        "email": (cliente.email if cliente else None) or cot.email_cliente,
        "numero_cotizacion": cot.numero,
        "total_items": total,
        "items_en_bodega": en_bodega,
        "items_despachados": despachados,
        "items_no_disponibles": no_dispon,
        "progreso_pct": progreso,
        "progreso_estados": progreso_estados,
        "estado": estado,
        "dias_restantes_oc": dias_restantes_oc,
        "dias_restantes_critico": worst_item_days,
        "documentos": {
            "excel_oc": True,
            "cot_formal_excel": bool(cot.archivo_formal),
            "cot_pdf": True,
            "cot_original_excel": bool(cot.archivo_original),
        },
    }


# --- Endpoints ---
@router.get("/counts")
def counts(db: Session = Depends(get_db), current_user: User = Depends(get_current_user)):
    ocs = db.query(OcCliente).join(OcCliente.cotizacion).all()
    # Estados de los ítems de TODAS las cotizaciones en una sola query
    # (antes: una query por OC → cientos de queries con el historial cargado)
    cot_ids = [oc.cotizacion_id for oc in ocs if oc.cotizacion_id]
    estados_por_cot: dict = {}
    if cot_ids:
        rows = (
            db.query(ItemCotizacion.cotizacion_id, ItemCotizacion.estado_item)
            .filter(ItemCotizacion.cotizacion_id.in_(cot_ids))
            .all()
        )
        for cot_id, estado in rows:
            estados_por_cot.setdefault(cot_id, []).append(estado)
    ocs_listas = 0
    items_listos = 0
    items_despachados = 0
    for oc in ocs:
        if not oc.cotizacion:
            continue
        estados = estados_por_cot.get(oc.cotizacion_id, [])
        en_b = sum(1 for e in estados if e == "en_bodega")
        desp = sum(1 for e in estados if e == "despachado")
        if en_b > 0:
            ocs_listas += 1
        items_listos += en_b
        items_despachados += desp
    return {
        "ocs_listas": ocs_listas,
        "items_listos": items_listos,
        "items_despachados": items_despachados,
    }


@router.get("/oc-clientes")
def oc_clientes(
    tab: str = "listas",
    q: Optional[str] = None,
    page: int = Query(1, ge=1),
    page_size: int = Query(50, ge=1, le=200),
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """List OCs by tab: listas | en_curso | historial

    Buscador de operador (2026-08-05): la pestaña y `q` bajan a SQL (antes se
    serializaban TODAS las cards por tecla y el filtro corría en Python sobre un
    haystack concatenado), con paginación honesta y orden determinista. La
    respuesta pasa de array pelado al sobre {items, total, page, page_size,
    q_efectivo, normalizado}; el único consumidor (DespachosPage.tsx) migra en
    el mismo commit. Cada card lleva `match: [{campo, valor}]` — el motivo de la
    coincidencia lo calcula el backend sobre la página, no el frontend.
    """
    if tab not in ("listas", "en_curso", "historial"):
        raise HTTPException(400, f"tab inválido: {tab}")

    # contains_eager: el join de siempre FILTRA pero no PUEBLA, y `cotizacion`
    # es lazy — sin esto, cada card de la página dispararía un SELECT extra.
    base = (
        db.query(OcCliente)
        .join(OcCliente.cotizacion)
        .options(contains_eager(OcCliente.cotizacion))
    )
    if tab == "listas":
        # Ítems en bodega > 0. (Un ítem 'en_bodega' implica despachados < total,
        # así que el descarte de estado == 'completado' del código anterior queda
        # cubierto por el mismo EXISTS: no se descartan filas después de paginar.)
        base = base.filter(exists().where(and_(
            ItemCotizacion.cotizacion_id == Cotizacion.id,
            ItemCotizacion.estado_item == "en_bodega",
        )))
    elif tab == "en_curso":
        base = base.filter(exists().where(and_(
            Despacho.oc_cliente_id == OcCliente.id,
            Despacho.estado == "en_preparacion",
        )))
    else:  # historial
        base = base.filter(exists().where(and_(
            Despacho.oc_cliente_id == OcCliente.id,
            Despacho.estado == "despachado",
        )))

    tokens = _normalizar_q(q)
    normalizado = False
    query = _filtro_q_oc_clientes(base, tokens) if tokens else base
    total = query.count()
    if tokens and total == 0 and any(any(c.isdigit() for c in t) for t in tokens):
        # Pasada B (solo si A dio 0 y hay dígitos): número de parte colapsado.
        query = _filtro_q_oc_clientes(base, tokens, con_colapsado=True)
        total = query.count()
        normalizado = total > 0

    # Sort by fecha_entrega ascending (urgent first), nulls last — ahora en SQL,
    # con desempate por id DESC: sin desempate, con OFFSET, MySQL puede repetir
    # una fila en la página 1 y perderla en la 2.
    ocs = (
        query.order_by(
            OcCliente.fecha_entrega.is_(None),
            OcCliente.fecha_entrega.asc(),
            OcCliente.id.desc(),
        )
        .offset((page - 1) * page_size)
        .limit(page_size)
        .all()
    )

    # Precarga en LOTE, SOLO sobre la página (antes: hasta 3 queries por OC
    # dentro del loop, sobre el histórico completo): ítems por cotización y
    # fichas de cliente por RUT. El filtro de pestaña por estado de despacho
    # ya bajó al WHERE (EXISTS), así que su precarga desapareció.
    cot_ids = [oc.cotizacion_id for oc in ocs if oc.cotizacion_id]
    items_por_cot: dict = {}
    if cot_ids:
        for it in (
            db.query(ItemCotizacion)
            .filter(ItemCotizacion.cotizacion_id.in_(cot_ids))
            .all()
        ):
            items_por_cot.setdefault(it.cotizacion_id, []).append(it)
    ruts = {oc.cotizacion.rut_cliente for oc in ocs if oc.cotizacion and oc.cotizacion.rut_cliente}
    clientes_por_rut: dict = {}
    if ruts:
        for cli in db.query(Cliente).filter(Cliente.rut.in_(ruts)).all():
            clientes_por_rut[cli.rut] = cli

    # Insignia de motivo: lote de embarques y despachos SOLO de la página.
    variantes_por_token = [_variantes_token(t) for t in tokens]
    colapsados = [_colapsar(t) for t in tokens if any(c.isdigit() for c in t)]
    emb_por_cot: dict = {}
    desp_por_oc: dict = {}
    if tokens:
        cot_por_item = {it.id: cid for cid, its in items_por_cot.items() for it in its}
        if cot_por_item:
            for item_id, emb_num, emb_awb_num in (
                db.query(EmbarqueItem.item_cotizacion_id, Embarque.numero, Embarque.awb_numero)
                .join(Embarque, Embarque.id == EmbarqueItem.embarque_id)
                .filter(EmbarqueItem.item_cotizacion_id.in_(list(cot_por_item)))
                .all()
            ):
                cot_id = cot_por_item.get(item_id)
                if cot_id is not None:
                    emb_por_cot.setdefault(cot_id, []).append((emb_num, emb_awb_num))
        oc_ids = [oc.id for oc in ocs]
        if oc_ids:
            for oc_id, d_num, d_guia, d_exp, d_transp in (
                db.query(Despacho.oc_cliente_id, Despacho.numero_despacho,
                         Despacho.numero_guia, Despacho.numero_expedicion,
                         Despacho.transportista)
                .filter(Despacho.oc_cliente_id.in_(oc_ids))
                .all()
            ):
                desp_por_oc.setdefault(oc_id, []).append((d_num, d_guia, d_exp, d_transp))

    def _match_de_card(oc) -> list:
        """[{campo, valor}] deduplicado por campo (primer valor gana)."""
        if not tokens:
            return []
        cot = oc.cotizacion
        encontrados: dict = {}

        def _agregar(campo, valor):
            if valor and campo not in encontrados:
                encontrados[campo] = valor

        if _matchea(oc.numero_oc, variantes_por_token):
            _agregar("oc_cliente", oc.numero_oc)
        if cot is not None:
            if _matchea(cot.numero, variantes_por_token):
                _agregar("cotizacion", cot.numero)
            if _matchea(cot.cliente, variantes_por_token):
                _agregar("cliente", cot.cliente)
            if _matchea(cot.rut_cliente, variantes_por_token):
                _agregar("rut", cot.rut_cliente)
            for it in items_por_cot.get(cot.id, []):
                if _matchea(it.numero_parte, variantes_por_token):
                    _agregar("numero_parte", it.numero_parte)
                if _matchea(it.descripcion, variantes_por_token) or \
                        _matchea(it.nombre_cat, variantes_por_token):
                    _agregar("repuesto", it.descripcion or it.nombre_cat)
                if _matchea(it.marca, variantes_por_token):
                    _agregar("marca", it.marca)
                # Acierto de la pasada colapsada: se declara aparte porque no se
                # puede mapear 6003113721 sobre 600-311-3721 carácter a carácter.
                if normalizado and it.numero_parte and any(
                        c in _colapsar(it.numero_parte) for c in colapsados):
                    _agregar("numero_parte_colapsado", it.numero_parte)
            for emb_num, emb_awb_num in emb_por_cot.get(cot.id, []):
                if _matchea(emb_num, variantes_por_token):
                    _agregar("embarque", emb_num)
                if _matchea(emb_awb_num, variantes_por_token):
                    _agregar("awb", emb_awb_num)
        for d_num, d_guia, d_exp, d_transp in desp_por_oc.get(oc.id, []):
            if _matchea(d_num, variantes_por_token):
                _agregar("despacho", d_num)
            if _matchea(d_guia, variantes_por_token):
                _agregar("guia", d_guia)
            if _matchea(d_exp, variantes_por_token):
                _agregar("expedicion", d_exp)
            if _matchea(d_transp, variantes_por_token):
                _agregar("transportista", d_transp)
        return [{"campo": c, "valor": v} for c, v in encontrados.items()]

    result = []
    for oc in ocs:
        card = _serialize_oc_card(
            db, oc,
            items=items_por_cot.get(oc.cotizacion_id, []),
            clientes_por_rut=clientes_por_rut,
        )
        if not card:
            continue
        card["match"] = _match_de_card(oc)
        result.append(card)

    return {
        "items": result,
        "total": total,
        "page": page,
        "page_size": page_size,
        "q_efectivo": " ".join(tokens),
        "normalizado": normalizado,
    }


@router.get("/oc-clientes/{oc_id}")
def oc_cliente_detail(
    oc_id: int,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    oc = db.query(OcCliente).filter(OcCliente.id == oc_id).first()
    if not oc:
        raise HTTPException(404, "OC no encontrada")
    card = _serialize_oc_card(db, oc)
    if not card:
        raise HTTPException(404, "OC sin cotización asociada")

    items = (
        db.query(ItemCotizacion)
        .filter(ItemCotizacion.cotizacion_id == oc.cotizacion_id)
        .all()
    )
    qty_already = _qty_already_dispatched(db, oc_id)
    # Tope físico: lo realmente RECIBIDO en bodega (una recepción parcial deja
    # despachable solo lo que llegó, no la cantidad completa de la venta)
    recibidos = _qty_recibida_utilizable(db, [it.id for it in items])

    cot = oc.cotizacion
    items_data = []
    for it in items:
        en_reclamo = bool(
            db.query(ReclamoProveedor)
            .filter(
                ReclamoProveedor.item_cotizacion_id == it.id,
                ReclamoProveedor.estado.in_(["pendiente", "reclamado"]),
            )
            .first()
        )
        cant = it.cantidad or 0
        qty_d = qty_already.get(it.id, 0)
        disponible = 0
        if it.estado_item == "en_bodega":
            disponible = max(_tope_fisico(it, recibidos) - qty_d, 0)

        # Per-item deadline & days remaining
        deadline = _item_deadline(it, cot, oc) if cot else None
        dias_rest: Optional[int] = None
        if deadline:
            try:
                dias_rest = business_days_remaining(deadline)
            except Exception:
                dias_rest = None

        items_data.append(
            {
                "id": it.id,
                "numero_parte": it.numero_parte,
                "descripcion": it.descripcion,
                "marca": it.marca,
                "cantidad": cant,
                "qty_despachada": qty_d,
                "qty_disponible": disponible,
                "estado_item": it.estado_item,
                "en_reclamo": en_reclamo,
                "plazo_entrega_max": it.plazo_entrega_max,
                "plazo_entrega_min": it.plazo_entrega_min,
                "deadline_item": deadline.isoformat() if deadline else None,
                "dias_restantes": dias_rest,
            }
        )

    despachos_data = []
    despachos = (
        db.query(Despacho)
        .filter(Despacho.oc_cliente_id == oc_id)
        .order_by(Despacho.id.desc())
        .all()
    )
    for d in despachos:
        despachos_data.append(
            {
                "id": d.id,
                "numero_despacho": d.numero_despacho,
                "numero_guia": d.numero_guia,
                "fecha_guia": d.fecha_guia.isoformat() if d.fecha_guia else None,
                "transportista": d.transportista,
                "estado": d.estado,
                "numero_expedicion": d.numero_expedicion,
                "guia_firmada": bool(d.guia_firmada),
                "fecha_firma": d.fecha_firma.isoformat() if d.fecha_firma else None,
                "guia_firmada_archivo": d.guia_firmada_archivo,
                "fecha_creacion": d.fecha_creacion.isoformat() if d.fecha_creacion else None,
                "fecha_despacho": d.fecha_despacho.isoformat() if d.fecha_despacho else None,
                "items_count": len(d.items),
            }
        )

    # Embarques that brought items of this OC
    item_ids = [it.id for it in items]
    embarques_data = []
    if item_ids:
        emb_rows = (
            db.query(Embarque)
            .join(EmbarqueItem, EmbarqueItem.embarque_id == Embarque.id)
            .filter(EmbarqueItem.item_cotizacion_id.in_(item_ids))
            .distinct()
            .all()
        )
        for emb in emb_rows:
            # Count items of THIS oc inside this embarque
            count = (
                db.query(EmbarqueItem)
                .filter(
                    EmbarqueItem.embarque_id == emb.id,
                    EmbarqueItem.item_cotizacion_id.in_(item_ids),
                )
                .count()
            )

            def _doc(value: Optional[str]):
                if not value:
                    return None
                value = value.strip()
                # is_file = the value corresponds to an actual file on disk
                # (covers both upload UUIDs and any other file que pueda haberse
                # colocado allí manualmente)
                is_file = _exists_in_docs(value) or (
                    _looks_like_upload(value) and _exists_in_docs(value)
                )
                return {
                    "value": value,
                    "is_file": is_file,
                    "filename": value if is_file else None,
                }

            embarques_data.append(
                {
                    "id": emb.id,
                    "numero": emb.numero or f"EMB-{emb.id}",
                    "estado": emb.estado,
                    "forwarder": emb.forwarder,
                    "fecha_despacho": emb.fecha_despacho,
                    "fecha_llegada_est": (
                        emb.fecha_llegada_est.isoformat() if emb.fecha_llegada_est else None
                    ),
                    "items_de_esta_oc": count,
                    "documentos": {
                        "awb": _doc(emb.awb),
                        "factura_comercial": _doc(emb.factura_comercial),
                        "packing_list": _doc(emb.packing_list),
                        "certificado_origen": _doc(emb.certificado_origen),
                        "doc_adicional": _doc(emb.doc_adicional),
                    },
                }
            )

    card["items"] = items_data
    card["despachos"] = despachos_data
    card["embarques"] = embarques_data
    return card


@router.post("/")
def create_despacho(
    payload: DespachoCreate,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    # El correlativo DSP-AAAA-#### se calcula sin lock: si dos despachos simultáneos
    # chocan en el UNIQUE de numero_despacho, se recalcula y se reintenta (máx. 3)
    # en vez de devolver un 500 al usuario.
    # Y el 1213/1205 se reintenta igual (paridad inversa con monza_router_despachos.py:673-685,
    # que lo ganó en la Fase 2): crear lockea los ÍTEMS primero y después las filas de
    # despacho, mientras cerrar/anular lockean el DESPACHO primero → orden inverso, ciclo
    # InnoDB. `cerrar` ya tiene este retry (ver más abajo); crear se quedó sin él y un deadlock
    # salía como 500 al usuario en vez de reintentarse solo.
    for _ in range(3):
        try:
            return _crear_despacho(db, payload, current_user)
        except IntegrityError as e:
            db.rollback()
            if "numero_despacho" not in str(getattr(e, "orig", e)):
                raise
        except OperationalError as e:
            db.rollback()
            code = getattr(getattr(e, "orig", None), "args", [None])[0]
            if code not in (1213, 1205):
                raise
    raise HTTPException(
        409, "No se pudo crear el despacho por creación simultánea de la misma OC: reintenta"
    )


def _crear_despacho(db: Session, payload: DespachoCreate, current_user: User):
    oc = db.query(OcCliente).filter(OcCliente.id == payload.oc_cliente_id).first()
    if not oc:
        raise HTTPException(404, "OC Cliente no encontrada")
    if not payload.items:
        raise HTTPException(400, "Debe incluir al menos 1 ítem")

    item_ids = [i.item_cotizacion_id for i in payload.items]
    # Una línea por ítem: dos líneas del mismo ítem burlarían la validación de
    # disponible (cada una se compararía sola contra el total).
    if len(set(item_ids)) != len(item_ids):
        raise HTTPException(400, "Hay ítems repetidos en el despacho: consolida la cantidad en una sola línea")
    # FOR UPDATE sobre los ítems: serializa despachos concurrentes de la misma OC
    # (el segundo espera aquí y valida contra lo que el primero ya commiteó).
    # populate_existing(): sin él, el identity map devolvería datos del snapshot viejo.
    items_db = (
        db.query(ItemCotizacion)
        .filter(
            ItemCotizacion.id.in_(item_ids),
            ItemCotizacion.cotizacion_id == oc.cotizacion_id,
        )
        .populate_existing()
        .with_for_update()
        .all()
    )
    if len(items_db) != len(set(item_ids)):
        raise HTTPException(400, "Hay ítems que no pertenecen a esta OC")

    items_by_id = {i.id: i for i in items_db}
    qty_already = _qty_already_dispatched(db, oc.id, con_lock=True)
    # Tope físico por lo RECIBIDO en bodega (recepción parcial ⇒ solo lo que llegó)
    recibidos = _qty_recibida_utilizable(db, item_ids)

    for item_in in payload.items:
        it = items_by_id.get(item_in.item_cotizacion_id)
        if not it:
            raise HTTPException(400, f"Ítem {item_in.item_cotizacion_id} no encontrado")
        if it.estado_item != "en_bodega":
            raise HTTPException(
                400,
                f"Ítem {it.numero_parte} no está disponible para despacho (estado: {it.estado_item})",
            )
        if item_in.qty_despachada <= 0:
            raise HTTPException(400, f"Cantidad inválida para {it.numero_parte}")
        tope = _tope_fisico(it, recibidos)
        disponible = tope - qty_already.get(it.id, 0)
        if item_in.qty_despachada > disponible + 0.001:
            if tope < (it.cantidad or 0):
                raise HTTPException(
                    400,
                    f"Cantidad excede lo RECIBIDO en bodega para {it.numero_parte} "
                    f"(recibido: {tope}, disponible: {max(disponible, 0)})",
                )
            raise HTTPException(
                400,
                f"Cantidad excede disponible para {it.numero_parte} (disp: {disponible})",
            )

    despacho = Despacho(
        numero_despacho=_next_numero_despacho(db),
        oc_cliente_id=payload.oc_cliente_id,
        numero_guia=payload.numero_guia,
        transportista=payload.transportista,
        numero_expedicion=payload.numero_expedicion,
        contacto_destinatario=payload.contacto_destinatario,
        direccion_entrega=payload.direccion_entrega,
        observaciones=payload.observaciones,
        estado="en_preparacion",
        usuario_creacion_id=getattr(current_user, "id", None),
    )
    db.add(despacho)
    db.flush()

    for item_in in payload.items:
        db.add(
            DespachoItem(
                despacho_id=despacho.id,
                item_cotizacion_id=item_in.item_cotizacion_id,
                qty_despachada=item_in.qty_despachada,
            )
        )

    db.commit()
    db.refresh(despacho)
    return {"id": despacho.id, "numero_despacho": despacho.numero_despacho}


@router.get("/{despacho_id}")
def get_despacho(
    despacho_id: int,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    d = db.query(Despacho).filter(Despacho.id == despacho_id).first()
    if not d:
        raise HTTPException(404, "Despacho no encontrado")
    oc = d.oc_cliente
    cot = oc.cotizacion if oc else None

    items_data = []
    for di in d.items:
        it = di.item_cotizacion
        items_data.append(
            {
                "id": di.id,
                "item_cotizacion_id": di.item_cotizacion_id,
                "numero_parte": it.numero_parte if it else None,
                "descripcion": it.descripcion if it else None,
                "marca": it.marca if it else None,
                "qty_despachada": di.qty_despachada,
            }
        )

    return {
        "id": d.id,
        "numero_despacho": d.numero_despacho,
        "oc_cliente_id": d.oc_cliente_id,
        "numero_oc": oc.numero_oc if oc else None,
        "cliente": cot.cliente if cot else None,
        "numero_guia": d.numero_guia,
        "fecha_guia": d.fecha_guia.isoformat() if d.fecha_guia else None,
        "transportista": d.transportista,
        "contacto_destinatario": d.contacto_destinatario,
        "direccion_entrega": d.direccion_entrega,
        "observaciones": d.observaciones,
        "estado": d.estado,
        "numero_expedicion": d.numero_expedicion,
        "guia_firmada": bool(d.guia_firmada),
        "fecha_firma": d.fecha_firma.isoformat() if d.fecha_firma else None,
        "guia_firmada_archivo": d.guia_firmada_archivo,
        "fecha_creacion": d.fecha_creacion.isoformat() if d.fecha_creacion else None,
        "fecha_despacho": d.fecha_despacho.isoformat() if d.fecha_despacho else None,
        "items": items_data,
    }


@router.put("/{despacho_id}")
def update_despacho(
    despacho_id: int,
    payload: DespachoUpdate,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    d = db.query(Despacho).filter(Despacho.id == despacho_id).first()
    if not d:
        raise HTTPException(404, "Despacho no encontrado")
    if d.estado == "anulado":
        raise HTTPException(400, "No se puede editar un despacho anulado")
    # Los datos de cabecera (transportista, N° guía, N° de expedición, contacto, dirección,
    # observaciones) pueden completarse/corregirse aunque el despacho ya esté cerrado o firmado:
    # el N° de expedición suele llegar del courier DESPUÉS del despacho.
    data = payload.dict(exclude_unset=True)
    # Excepción: con guía electrónica viva, numero_guia es el folio del SII y no se pisa a mano.
    if "numero_guia" in data:
        _rechazar_si_pisa_folio(db, d, data["numero_guia"])
    # fecha_guia llega como texto y la columna es Date: se convierte y valida ANTES del
    # setattr genérico (si no, SQLAlchemy guardaría el string crudo). Se saca del dict para
    # que el bucle de abajo no la pise con el valor sin parsear.
    if "fecha_guia" in data:
        d.fecha_guia = _parse_fecha_guia(data.pop("fecha_guia"))
    for field, value in data.items():
        setattr(d, field, value)
    db.commit()
    return {"ok": True}


@router.post("/{despacho_id}/cerrar")
def cerrar_despacho(
    despacho_id: int,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    # Retry 1213/1205 (regla de la casa): cerrar ahora toma locks (despacho + ítems)
    # y puede caer víctima de un deadlock contra crear/anular concurrentes.
    for _ in range(3):
        try:
            return _cerrar_despacho_tx(db, despacho_id)
        except OperationalError as e:
            db.rollback()
            code = getattr(getattr(e, "orig", None), "args", [None])[0]
            if code not in (1213, 1205):
                raise
    raise HTTPException(409, "Conflicto de concurrencia al cerrar el despacho: reintenta")


def _cerrar_despacho_tx(db: Session, despacho_id: int):
    # FOR UPDATE sobre el despacho: serializa contra anular_despacho (que también
    # lockea) y contra la emisión de la guía. populate_existing(): datos frescos
    # aunque el snapshot REPEATABLE READ sea anterior.
    d = (
        db.query(Despacho)
        .filter(Despacho.id == despacho_id)
        .populate_existing()
        .with_for_update()
        .first()
    )
    if not d:
        raise HTTPException(404, "Despacho no encontrado")
    if d.estado != "en_preparacion":
        raise HTTPException(400, "Solo se pueden cerrar despachos en preparación")

    # Ancla canónica de la casa (patrón recepcion_nacional._cerrar): lockear los
    # ItemCotizacion afectados en UNA query, orden id ASC, antes de mutar estados.
    item_ids = sorted({di.item_cotizacion_id for di in d.items if di.item_cotizacion_id})
    if item_ids:
        (
            db.query(ItemCotizacion)
            .filter(ItemCotizacion.id.in_(item_ids))
            .order_by(ItemCotizacion.id.asc())
            .populate_existing()
            .with_for_update()
            .all()
        )

    # CERRAR PRIMERO y flush: la cobertura de abajo cuenta SOLO despachos cerrados
    # (incluido este). Sin esto, la última tanda nunca voltearía la línea; y contar
    # abiertos (bug G16) marcaba 'despachado' prematuro con tandas en preparación.
    d.estado = "despachado"
    d.fecha_despacho = datetime.now()
    db.flush()

    # Recolectar embarques afectados para evaluar auto-transición a "despachado"
    embarque_ids_afectados = set()
    # Cantidad acumulada por ítem en los despachos CERRADOS de la OC (incluye este).
    # La línea pasa a "despachado" solo cuando queda cubierta completa: un cierre
    # parcial deja el remanente en bodega, despachable y facturable después.
    qty_total = _qty_dispatched_closed(db, d.oc_cliente_id, con_lock=True)
    for di in d.items:
        it = di.item_cotizacion
        if it and it.estado_item == "en_bodega":
            if qty_total.get(it.id, 0) + 0.001 < (it.cantidad or 0):
                continue
            it.estado_item = "despachado"
            # Buscar el embarque que trajo este item
            ei = (
                db.query(EmbarqueItem)
                .filter(EmbarqueItem.item_cotizacion_id == it.id)
                .first()
            )
            if ei:
                embarque_ids_afectados.add(ei.embarque_id)

    # Auto-transición: si TODOS los items de un embarque están despachados,
    # marcar el embarque como "despachado"
    db.flush()
    for emb_id in embarque_ids_afectados:
        item_ids_emb = [
            r[0] for r in db.query(EmbarqueItem.item_cotizacion_id)
            .filter(EmbarqueItem.embarque_id == emb_id).all()
        ]
        if not item_ids_emb:
            continue
        items_emb = (
            db.query(ItemCotizacion)
            .filter(ItemCotizacion.id.in_(item_ids_emb))
            .all()
        )
        todos_despachados = all(i.estado_item == "despachado" for i in items_emb)
        if todos_despachados:
            emb = db.query(Embarque).filter(Embarque.id == emb_id).first()
            if emb and emb.estado != "despachado":
                emb.estado = "despachado"

    oc = d.oc_cliente
    if oc and oc.cotizacion:
        try:
            crear_notificacion(
                db,
                rol="ventas",
                severidad="info",
                titulo=f"Despacho {d.numero_despacho} completado",
                mensaje=f"OC {oc.numero_oc} - {oc.cotizacion.cliente} · {len(d.items)} ítems despachados",
                entidad_tipo="despacho",
                entidad_id=d.id,
                link=f"/despachos?id={d.id}",
                regla=f"despacho_completado_{d.id}",
            )
        except Exception:
            # don't fail the dispatch if notification fails
            pass

    db.commit()
    return {"ok": True, "numero_despacho": d.numero_despacho}


@router.post("/{despacho_id}/firmar")
def firmar_despacho(
    despacho_id: int,
    payload: FirmarIn,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Marca la guía de despacho como FIRMADA (entregada y firmada por el cliente).
    Solo con la guía firmada Contabilidad puede emitir la factura de esos ítems."""
    d = db.query(Despacho).filter(Despacho.id == despacho_id).first()
    if not d:
        raise HTTPException(404, "Despacho no encontrado")
    if d.estado != "despachado":
        raise HTTPException(400, "Primero confirme (cierre) el despacho; luego marque la guía como firmada")
    if payload.numero_guia:
        # Con guía electrónica viva, el N° correcto ya es el folio del SII: se
        # bloquea el reemplazo manual (la firma en sí sigue funcionando sin tocar el N°).
        _rechazar_si_pisa_folio(db, d, payload.numero_guia)
        d.numero_guia = payload.numero_guia
    fecha = None
    if payload.fecha_firma:
        try:
            fecha = datetime.strptime(payload.fecha_firma[:10], "%Y-%m-%d")
        except (ValueError, TypeError):
            fecha = None
    # La guía firmada (foto/PDF) es OBLIGATORIA: es el respaldo de la entrega y
    # la condición para que Contabilidad pueda facturar esos ítems.
    if not payload.archivo:
        raise HTTPException(400, "Debes adjuntar la guía de despacho firmada por el cliente")
    if not _exists_in_docs(payload.archivo):
        raise HTTPException(400, "El documento de la guía firmada no existe (súbalo primero)")
    d.guia_firmada_archivo = payload.archivo
    d.guia_firmada = 1
    d.fecha_firma = fecha or datetime.now()
    d.usuario_firma_id = getattr(current_user, "id", None)
    db.commit()
    return {
        "ok": True, "guia_firmada": True, "numero_guia": d.numero_guia,
        "guia_firmada_archivo": d.guia_firmada_archivo,
    }


@router.delete("/{despacho_id}")
def anular_despacho(
    despacho_id: int,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    # Retry 1213/1205, igual que cerrar y crear (paridad inversa con
    # monza_router_despachos.py:1113-1121): anular lockea el DESPACHO primero y crear lockea
    # los ÍTEMS primero, así que un anular concurrente con una creación de la misma OC puede
    # caer víctima del deadlock. Sin el retry salía como 500.
    for _ in range(3):
        try:
            return _anular_despacho_tx(db, despacho_id, current_user)
        except OperationalError as e:
            db.rollback()
            code = getattr(getattr(e, "orig", None), "args", [None])[0]
            if code not in (1213, 1205):
                raise
    raise HTTPException(409, "Conflicto de concurrencia al anular el despacho: reintenta")


def _anular_despacho_tx(db: Session, despacho_id: int, current_user: User):
    # FOR UPDATE: serializa contra la emisión de la guía (que también bloquea el
    # despacho en _reclamar_emision) — sin el lock, anular y emitir simultáneos
    # podían dejar una guía SII viva sobre un despacho anulado.
    d = (
        db.query(Despacho)
        .filter(Despacho.id == despacho_id)
        .populate_existing()
        .with_for_update()
        .first()
    )
    if not d:
        raise HTTPException(404, "Despacho no encontrado")
    if d.estado != "en_preparacion":
        raise HTTPException(400, "Solo se pueden anular despachos en preparación")
    # La guía 52 se emite con el despacho aún en preparación: anular acá dejaría un
    # documento tributario legal huérfano y la mercadería libre para emitir OTRA
    # guía por lo mismo (doble emisión ante el SII). Se bloquea mientras la guía viva.
    # incluir_ambiguo=True: un claim VENCIDO sobre una emisión que Wasabil nunca
    # confirmó (uuid NULL + en_vuelo_desde puesto) también bloquea; si no, la
    # mercadería volvía a bodega y salía una SEGUNDA guía 52 REAL al SII. Se pasa SOLO
    # acá porque anular es irreversible (paridad con MonzaParts,
    # monza_router_despachos.py:_anular_despacho_tx).
    dte = _guia_electronica_activa(db, d.id, con_lock=True, incluir_ambiguo=True)
    if dte:
        if dte.folio:
            raise HTTPException(
                409,
                f"Este despacho tiene guía electrónica SII emitida (folio {dte.folio}): "
                "anúlala primero en Wasabil (anulación/nota de crédito) y luego anula el despacho",
            )
        if dte.uuid is None and dte.en_vuelo_desde is not None and not claim_vigente(dte):
            # Ambiguo con el claim vencido: "esperar" ya no resuelve nada, la única
            # salida es Reintentar (adopta el documento si existe en Wasabil, o
            # re-emite tras confirmar su ausencia). Mismo texto que el de facturas
            # (ambiguo_sin_resolver en routers/contabilidad.py).
            raise HTTPException(
                409,
                "No hay confirmación de Wasabil sobre esta emisión (se cortó la comunicación): "
                "la guía PUEDE existir ya ante el SII. Usa «Reintentar» para que el sistema lo "
                "verifique; si confirma que no se emitió, podrás anular",
            )
        raise HTTPException(
            409,
            "Este despacho tiene una emisión de guía SII en curso: espera el resultado "
            "(Emitida o Fallida) antes de anular",
        )
    d.estado = "anulado"
    # Simetría con cerrar_despacho: si este despacho sostenía (junto a otros) la
    # cobertura completa de una línea, al anularlo el remanente vuelve a bodega.
    # Con la cobertura por CERRADOS esto es casi inalcanzable (un cerrado no se
    # anula), pero queda como red de seguridad para datos legados.
    db.flush()
    qty_total = _qty_dispatched_closed(db, d.oc_cliente_id)
    for di in d.items:
        it = di.item_cotizacion
        if (
            it
            and it.estado_item == "despachado"
            and qty_total.get(it.id, 0) + 0.001 < (it.cantidad or 0)
        ):
            it.estado_item = "en_bodega"
    # DEFENSA (mesa redonda G16): la auto-transición del embarque a 'despachado'
    # era one-way. Si alguna línea de un embarque 'despachado' ya no está
    # despachada (reversa de arriba o estado atascado legado), el embarque vuelve
    # a 'en_bodega' — el estado que deja Bodega al cerrar la recepción. Solo BAJA,
    # nunca sube; los ítems nacionales (sin EmbarqueItem) simplemente no aplican.
    db.flush()
    item_ids_anulados = [di.item_cotizacion_id for di in d.items if di.item_cotizacion_id]
    if item_ids_anulados:
        emb_ids = {
            r[0] for r in db.query(EmbarqueItem.embarque_id)
            .filter(EmbarqueItem.item_cotizacion_id.in_(item_ids_anulados)).all()
        }
        for emb_id in emb_ids:
            emb = db.query(Embarque).filter(Embarque.id == emb_id).first()
            if not emb or emb.estado != "despachado":
                continue
            ids_emb = [
                r[0] for r in db.query(EmbarqueItem.item_cotizacion_id)
                .filter(EmbarqueItem.embarque_id == emb_id).all()
            ]
            items_emb = (
                db.query(ItemCotizacion).filter(ItemCotizacion.id.in_(ids_emb)).all()
                if ids_emb else []
            )
            if items_emb and not all(i.estado_item == "despachado" for i in items_emb):
                emb.estado = "en_bodega"
    db.commit()
    return {"ok": True}


# --- Serve documents uploaded via /api/compras/docs/upload ---
@router.get("/docs/{filename}")
def serve_doc(
    filename: str,
    current_user: User = Depends(get_current_user),
):
    """Serve a previously uploaded document. Authenticated access only.

    Path traversal is prevented by validating the filename format and resolving
    the final path against the uploads/docs directory.
    """
    # Strict filename validation: alphanumeric + dot + dash + underscore only
    if not re.match(r"^[A-Za-z0-9._-]{1,255}$", filename):
        raise HTTPException(400, "Nombre de archivo inválido")

    # Resolve and ensure it stays inside DOCS_DIR
    full_path = os.path.abspath(os.path.join(_DOCS_DIR, filename))
    if not full_path.startswith(_DOCS_DIR + os.sep):
        raise HTTPException(400, "Ruta inválida")
    if not os.path.isfile(full_path):
        raise HTTPException(404, "Documento no encontrado")

    return FileResponse(full_path, filename=filename)
